### ISSUE TITLE
ZoneMemberCountry assumes a single excluded_postal_codes regex pattern

### ISSUE THREAD

**Issue by lukestokes** [commerceguys/tax#13]
In pt_vat.json, we have stuff like this: `"excluded_postal_codes": "\/(9)[0-4][0-9]{2}-[0-9]{3}\/, \/(9)[5-9][0-9]{2}-[0-9]{3}\/"` which leads to this `PHP E_WARNING preg_match() [<a href='function.preg-match'>function.preg-match</a>]: Unknown modifier ',' (pid: 13936) in vendor/commerceguys/zone/src/Model/ZoneMemberCountry.php on line 101`

**Comment by bojanz** [comment]
Fixed in 625487e11513ba3aa686ca7b1df21b6853b5311e
