### ISSUE TITLE
Question: Are there any current circumstances where TaxResolver::resolveTypes() return more than one item?

### ISSUE THREAD

**Issue by neilcrookespm** [commerceguys/tax#15]
I appreciate it's possible this could be required, so I'm not questioning why returning multiple types is necessary, but I would like to know what context and physical/non-physical taxable item combination could cause the current codebase to return multiple types from TaxResolver::resolveTypes(), or indeed return multiple rates from TaxResolver::resolveRates() or multiple amounts from TaxResolver::resolveAmounts(), for testing purposes.

**Comment by dwkitchen** [comment]
For any one product it will only be in one tax type and have one valid tax rate for each zone, however more than one zone may be active.

Canada has compound taxes, the the resolver could return up to 3 zones, national, state and city. Each would have its own Type and Rate.

**Comment by neilcrookespm** [comment]
Thanks for your reply @dwkitchen. Understood. So is it just that there isn't any zones data from n the resources directory that would trigger this scenario? Is it in the plan for the repo to include Canadian tax zones and types?

**Comment by bojanz** [comment]
Yes, right now no data triggers this scenario. 
Canada has federal and state taxes (GST + PST) which require being able to return multiple tax types (and because of that multiple tax rates&amounts).
I would welcome a PR for canadian tax types (and every other tax type other than US sales tax, since that one has a million combinations).

**Comment by neilcrookespm** [comment]
Thanks for the confirmation guys. I'll help out with PRs as soon and as often as I can.
