### ISSUE TITLE
Unable to install 0.5 alongside commerceguys/addressing 0.5

### ISSUE THREAD

**Issue by colinodell** [commerceguys/tax#17]
This package requires the `dev-master` version of `commerceguys/addressing` - I therefore cannot install version 0.5 of that package:

![2015-03-11_10-17-45](https://cloud.githubusercontent.com/assets/202034/6598134/ed8b9d5e-c7d7-11e4-9081-aa5a5a32796f.png)

**Can the `composer.json` requirement be changed to `~0.5` (for stable releases) or `*` (any version)?**

See also: https://github.com/commerceguys/pricing/issues/10

**Comment by colinodell** [comment]
Looks like the `commerceguys/zone` dependency might have the same issue too

**Comment by bojanz** [comment]
Thanks.
