### ISSUE TITLE
VAT on Shipping in the EU

### ISSUE THREAD

**Issue by dwkitchen** [commerceguys/tax#18]
# Description

I have now had confirmation on two different methods of calculating the VAT due on shipping services in the EU.

In the UK the VAT on shipping is at the highest rate of the items on the order. I.e. if there is 2 items both at 0%, shipping is 0%, however if there is one at 0% and 1 at 20% the VAT on the shipping is 20%.
https://www.gov.uk/government/publications/vat-notice-70024-postage-and-delivery-charges/vat-notice-70024-postage-and-delivery-charges

In Sweden however the VAT on the shipping is proportionately calculated based on the rates of all the items.
http://www.skatteverket.se/rattsinformation/skrivelser2005/02/skrivelser20020913.4.18e1b10334ebe8bc80001578.html

This information has come from an issue on the Drupal Commerce 1.x EU VAT Module. https://www.drupal.org/node/1667624 
# Solution Idea

We will need a EuShippingTaxRateResolver.

It will need to be able to calculate the rate based on the Taxable (the shipping charge) and the other Taxables on the order.

We would need to know the Rate that has already been resolved on the other Taxables on the order.

**Comment by bojanz** [comment]
While definitely needed, this probably makes more sense in the pricing library (or a shipping one, once that gets created).

(Also, Sweden doesn't resolve a predefined tax rate, it just returns a raw amount, so the resolvers are the wrong level for this logic)

**Comment by pereriksson** [comment]
For Sweden these calculation rules are used in other areas as well - order discounts, invoice fees, service fees etc, since these things are also "attributable" to the items of the order.
The behaviour appears to be used for order discounts in Germany as well (see axel.rutz work in issue 2276227). Can the logic be implemented once and then reused by all line item types (where it is needed)?

**Comment by dwkitchen** [comment]
I'm not sure why it would make sense for the Tax calculation on shipping to be part of some other library. We do need to work out what the guidance for the rate to apply to shipping is for each EU country, a call for international commerce people is needed.

This is also the same way for calculating the rate of a fixed price whole order discount where there are mixed rates. I.e. £5 off your order when you spend over £50. This seems to be consistent across Europe.

Again in the UK fees are the same as shipping where it is the highest rate, but as we need this functionality for calculating tax on Fees, Shipping and Discounts it seems we should be providing here.

**Comment by dolcey** [comment]
I've been following your restlessness and I want to inform another drawback of the same module, in Spain, the IVA shipping is a fixed level 21%, and for example, in my orders products have reduced VAT, 10% and therefore is translated to VAT shipping, and enters an error.

Any help to correct this, will be assessed.

**Comment by Archanium** [comment]
Then there is Denmark, where, if you use the Danish postal service, and you don't charge more than their shipping cost, and it's not for a company address, it's actually tax-free, but if you charge more, there tax based on the entirety of the shipping cost (at the default rate of 25%)

If you on the other hand split the shipping into a handling fee and a shipping cost (that's again the same as the postal service's shipping price) you won't be charged VAT on the shipping cost, but just the handling fee.

**Comment by pereriksson** [comment]
Maybe there should be an opportunity to use rules for more specific use cases. Maybe there is a general use case for shipping VAT in Denmark that this module should support first?

**Comment by Archanium** [comment]
The general rule is that shipping is inclusive 25% VAT :)

**Comment by MathiasGmeiner** [comment]
If shipping is done with DHL, DPD or another private company in austria 20% VAT is collected.

**Comment by theaduo** [comment]
@Archanium Is this still true or has it changed now? I can't find anything about it on google but I don't know how to search in Danish.

> Then there is Denmark, where, if you use the Danish postal service, and you don't charge more than their shipping cost, and it's not for a company address, it's actually tax-free, but if you charge more, there tax based on the entirety of the shipping cost (at the default rate of 25%)

If so, is there a link where I can read more information about this? Thanks!

**Comment by dwkitchen** [comment]
@theaduo & @Archanium 
The same exists in the UK if you "defray" the costs of Royal Mail postage to the customer with no additional service charges for "packaging" they are also exempt from VAT

**Comment by dmnc** [comment]
In the UK VAT is generally prorated based on the basket of goods.

Closing this as I don't believe it is within the scope of this package. Thank you for raising though.
