### ISSUE TITLE
Add the 10% CZ rate

### ISSUE THREAD

**Issue by bojanz** [commerceguys/tax#38]
http://www.vatlive.com/european-news/czech-approves-new-10-reduced-vat-rate/
https://www.drupal.org/node/2412207

Waiting for dwkitchen's feedback on whether it should be Second Reduced or Super Reduced.
Traditionally the Super Reduced rate is the one below 5%, but we also rarely use Second.

**Comment by dwkitchen** [comment]
We had a similar discussion about Ireland. We use "Second Reduced" and "Intermediate" for reduced rates that don't fall in to the EU defined Super-Reduced category.

In this case the new rate is lower than current reduced rate, so we would call it Second Reduced.

If the new rate was between the reduced and the standard rate we would call it the Intermediate rate; like in France.

**Comment by bojanz** [comment]
Great, thanks for confirming.

**Comment by bojanz** [comment]
Btw, I added a Super Reduced rate for Croatia: 1a8e3bd342217f9fb13ab75f56e4d2e656507806

Sites called it Super Reduced, I know 5% is around the cutoff rule, so I went with that.
