### ISSUE TITLE
Cant Process Taxable Object

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [commerceguys/tax#41]
I Create Tax Processing function, but i dont know how to implement "taxable" object to Resolve Rate and Type.

**Comment by el-seirh** [comment]
There doesn't seem to be a instantiable class, just an interface. But you can easily create it yourself. All it does is distinguish wether an item is physical or not.
Just pass this to the resolver:

```
class MyTaxable implements \CommerceGuys\Tax\TaxableInterface {
public function isPhysical(){
        return false; // or true 
    }
}

**Comment by bojanz** [comment]
Correct. Your product entity should implement the taxable interface.
