### ISSUE TITLE
No TaxTypeResolver for Switzerland?

### ISSUE THREAD

**Issue by el-seirh** [commerceguys/tax#47]
Hi there.
In your readme you mention: "Predefined tax rates for EU countries and Switzerland."
Browsing through the project however I see a EuTaxTypeResolver, a DefaultTaxTypeResolver and a CanadaTaxTypeResolver.
But none for Switzerland. However I can see that there is a commerceguys/tax/resources/tax_type/ch_vat.json file.

So why no ChTaxTypeResolver? Should I create one by pull request?

Anyway, thanks guys for this amazing library!

**Comment by bojanz** [comment]
Switzerland is handled by the DefaultTaxTypeResolver, I don't know of any special Swiss logic that would require it to have its own resolver?

**Comment by el-seirh** [comment]
Well that is ... probably a pretty good point. Sorry I didn't see that. I somehow just assumed that each type of tax legislation has its own resolver. But I guess the swiss logic isn't that complex indeed.
Thanks for the intel and never mind. ;)
