### ISSUE TITLE
Swiss tax rates change on 01/01/2018

### ISSUE THREAD

**Issue by luksak** [commerceguys/tax#54]
There will be new tax rates in switzerland from 01/01/2018: https://www.ch.ch/de/mehrwertsteuersatz-schweiz/

**Comment by el-seirh** [comment]
@luksak I just made a pull request for that: https://github.com/commerceguys/tax/pull/55
CHeers!

**Comment by bojanz** [comment]
Merged. Thank you both.

**Comment by dmnc** [comment]
@bojanz could we get a release for this please?
