### ISSUE TITLE
Finland: standard VAT to go up to 25.5% on Sept 1, 2024

### ISSUE THREAD

**Issue by simohell-fi** [commerceguys/tax#92]
The change in the law has not yet passed the final stage of approval, so I guess we need to still wait a bit - but the change is coming really soon so best to be ready on advance to merge and release.

Finnish Tax Administration documentarion
https://www.vero.fi/en/businesses-and-corporations/taxes-and-charges/vat/rates-of-vat/new-vat-rate-from-1-september-2024--instructions-for-vat-reporting/

**Comment by dmnc** [comment]
Thanks for the heads up @simohell-fi. Please see #95.
